<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>VirtualMonitorsUniverse.Server</AssemblyName>
    <RootNamespace>VirtualMonitorsUniverse.Server</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>
