namespace VirtualMonitorsUniverse.Server;

/// <summary>
/// Small, page-scoped web-client enhancements. Keeping these behaviors separate
/// from the base renderer makes regression fixes auditable and avoids rewriting
/// working Terminal/fullscreen and monitor-property UI code.
/// </summary>
internal static class WebPageEnhancements
{
    public static string ForTitle(string title) => title switch
    {
        "Settings" => Settings,
        "Monitors" => Monitors,
        "Log" => Log,
        _ when title.StartsWith("Terminal ", StringComparison.Ordinal) => Terminal,
        _ => string.Empty
    };

    public const string GlobalNavButtons = """
<div class="globalTools">
  <button id="globalScreenshotToggle" class="fullscreenToggle iconButton" type="button" aria-label="Take monitor screenshot" title="Take monitor screenshot">📷</button>
  <div id="globalScreenshotMenu" class="globalScreenshotMenu hidden"></div>
</div>
<button id="fullscreenToggle" class="fullscreenToggle iconButton" type="button" aria-label="Toggle fullscreen" title="Enter fullscreen">⛶</button>
""";

    public const string Global = """
<style>
.globalTools{position:relative;display:flex;align-items:center}.globalScreenshotMenu{position:absolute;right:0;top:54px;background:#fff;color:#222;border:1px solid #bbb;border-radius:6px;min-width:190px;padding:6px;box-shadow:0 3px 12px #0003;z-index:1400}.globalScreenshotMenu button{display:block;width:100%;padding:9px 10px;border:0;background:transparent;text-align:left;border-radius:4px;cursor:pointer}.globalScreenshotMenu button:hover,.globalScreenshotMenu button:focus-visible{background:#eef1f4}.vmuToast{position:fixed;right:16px;bottom:16px;z-index:5000;padding:9px 12px;border-radius:7px;background:#282d33;color:#fff;box-shadow:0 3px 12px #0005;font-size:13px}.vmuToast.error{background:#8b1f28}.vmuMenuScreenshot{display:block;width:100%;text-align:left;padding:8px 9px;border:0;background:transparent;border-radius:4px;cursor:pointer}.vmuMenuScreenshot:hover{background:#eef1f4}.builtInAvatar{object-fit:contain;background:transparent}.navAvatarEmoji .builtInAvatar,.navAvatar.builtInAvatar{width:24px;height:24px}.avatarEmoji .builtInAvatar,.cardAvatar.builtInAvatar{width:30px;height:30px}.avatarpicker .avatargrid{grid-template-columns:repeat(4,60px)!important;gap:6px!important;padding:9px!important}.avatarpicker .avatargrid button{width:60px!important;height:58px!important;padding:4px!important;display:flex!important;align-items:center!important;justify-content:center!important}.avatarpicker [data-animal] img{width:50px!important;height:50px!important;object-fit:contain!important}.avatarcurrent{width:64px!important;height:60px!important}.avatarcurrent img{width:50px!important;height:50px!important;object-fit:contain!important;border-radius:5px}.vmuAppHome{height:60px;width:54px;display:flex;align-items:center;justify-content:center;border-right:1px solid #555;color:#fff;text-decoration:none;flex:0 0 auto}.vmuAppHome:hover,.vmuAppHome:focus-visible{background:#2b3036;outline:none}.vmuAppGlyph{position:relative;width:34px;height:28px;display:block}.vmuAppGlyph .screenA,.vmuAppGlyph .screenB{position:absolute;border:2px solid #dce7f5;border-radius:2px;background:#253244}.vmuAppGlyph .screenA{left:1px;top:2px;width:22px;height:15px}.vmuAppGlyph .screenB{right:1px;bottom:2px;width:22px;height:15px}.vmuAppGlyph .v{position:absolute;inset:0;z-index:2;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;font-size:17px;text-shadow:0 1px 2px #000}.monitorMenu label.vmuAudioDisabled{opacity:.45}.monitorMenu input.vmuMouseToggle{pointer-events:auto}.monitorMenu label.vmuMouseLabel{cursor:pointer}
</style>
<script>
(() => {
  if(window.vmuGlobalTools)return;window.vmuGlobalTools=true;
  const camera=document.getElementById('globalScreenshotToggle'),cameraMenu=document.getElementById('globalScreenshotMenu');
  const navHost=document.getElementById('monitorNavHost');
  if(navHost&&!document.querySelector('.vmuAppHome')){const home=document.createElement('a');home.className='vmuAppHome';home.href='/';home.title='Virtual Monitors Universe';home.setAttribute('aria-label','Virtual Monitors Universe home');home.innerHTML='<span class="vmuAppGlyph" aria-hidden="true"><i class="screenA"></i><i class="screenB"></i><b class="v">V</b></span>';navHost.parentElement?.insertBefore(home,navHost);}
  function toast(message,error=false){document.getElementById('vmuToast')?.remove();const box=document.createElement('div');box.id='vmuToast';box.className='vmuToast'+(error?' error':'');box.textContent=message;document.body.appendChild(box);setTimeout(()=>box.remove(),2600);}
  async function pngPromise(name){const response=await fetch('/api/monitors/'+encodeURIComponent(name)+'/thumbnail?force=1&t='+Date.now(),{cache:'no-store'});if(!response.ok)throw new Error('VMU could not capture the monitor image.');const bitmap=await createImageBitmap(await response.blob());try{const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;const context=canvas.getContext('2d',{alpha:false});if(!context)throw new Error('Canvas capture is unavailable.');context.drawImage(bitmap,0,0);return await new Promise((resolve,reject)=>canvas.toBlob(x=>x?resolve(x):reject(new Error('PNG encoding failed.')),'image/png'));}finally{bitmap.close();}}
  window.vmuCaptureMonitor=async name=>{if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined'||typeof createImageBitmap==='undefined')throw new Error('Screenshot is unavailable in this browser/context.');const promise=pngPromise(name);await navigator.clipboard.write([new ClipboardItem({'image/png':promise})]);toast('Monitor screenshot copied to clipboard.');};
  async function captureFromClick(name){try{await window.vmuCaptureMonitor(name);}catch(error){toast(error?.message||'Screenshot failed.',true);}}

  let avatarCatalog=null,monitorCache=null;
  function monitorByName(name){return monitorCache?.find(x=>x.configuration.name===name)||null;}
  function avatarUrl(id){return '/api/avatars/'+encodeURIComponent(id)+'?v='+(avatarCatalog?.revision??0);}
  function avatarMarkup(id,cls='builtInAvatar'){return '<img class="'+cls+'" src="'+avatarUrl(id)+'" alt="">';}
  function renderBuiltInAvatars(){if(!avatarCatalog)return;const valid=new Set(avatarCatalog.ids);document.querySelectorAll('.monitorNavWrap[data-monitor]').forEach(w=>{const m=monitorByName(w.dataset.monitor);if(!m||m.configuration.avatarKind!=='animal'||!valid.has(m.configuration.avatarValue))return;const slot=w.querySelector('.navAvatarEmoji');if(slot)slot.innerHTML=avatarMarkup(m.configuration.avatarValue);});document.querySelectorAll('.monitorcard[data-id]').forEach(card=>{const m=monitorCache?.find(x=>x.configuration.vmuId===card.dataset.id);if(!m||m.configuration.avatarKind!=='animal'||!valid.has(m.configuration.avatarValue))return;const slot=card.querySelector('.avatarSlot');if(slot)slot.innerHTML=avatarMarkup(m.configuration.avatarValue,'cardAvatar builtInAvatar');});const picker=document.querySelector('.avatarpicker');if(!picker)return;picker.querySelectorAll('[data-animal]').forEach(button=>{const id=button.dataset.animal;if(!valid.has(id)){button.remove();return;}button.innerHTML=avatarMarkup(id);});if(picker.dataset.kind==='animal'&&valid.has(picker.dataset.selected))picker.querySelector('.avatarcurrent').innerHTML=avatarMarkup(picker.dataset.selected);}
  async function loadAvatarData(){try{const [catalog,monitors]=await Promise.all([fetch('/api/avatars',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();}),fetch('/api/monitors',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();})]);avatarCatalog=catalog;monitorCache=monitors;renderBuiltInAvatars();decorateMenus();}catch{}}
  setTimeout(()=>{window.vmuAnimalEmoji=id=>avatarMarkup(id);renderBuiltInAvatars();},0);

  async function setMouseCapability(monitor,enabled){const c=monitor.configuration;const payload={name:c.name,title:c.title,width:c.width,height:c.height,refreshRate:c.refreshRate,portrait:c.portrait,remoteAccess:c.remoteAccess,securityMode:c.securityMode,password:null,regenerateApiKey:false,collaborationClipboard:c.collaborationClipboard,collaborationMouse:enabled,collaborationKeyboard:c.collaborationKeyboard};const response=await fetch('/api/monitors/'+encodeURIComponent(c.name),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){let message='Mouse capability could not be changed.';try{message=(await response.json()).error||message;}catch{}throw new Error(message);}return await response.json();}
  function decorateMenus(){document.querySelectorAll('.monitorNavWrap').forEach(w=>{const menu=w.querySelector('.monitorMenu');if(!menu)return;const monitor=monitorByName(w.dataset.monitor);if(!menu.querySelector('.vmuMenuScreenshot')){const hr=menu.querySelector('hr');const shot=document.createElement('button');shot.type='button';shot.className='vmuMenuScreenshot';shot.textContent='📷 Screenshot';shot.onclick=e=>{e.preventDefault();e.stopPropagation();w.classList.remove('menuOpen');captureFromClick(w.dataset.monitor);};if(hr)menu.insertBefore(shot,hr);else menu.appendChild(shot);}const labels=[...menu.querySelectorAll('label')];const mouseLabel=labels.find(x=>/Mouse/i.test(x.textContent||''));if(mouseLabel&&monitor){const input=mouseLabel.querySelector('input');if(input&&!input.classList.contains('vmuMouseToggle')){input.disabled=false;input.checked=monitor.configuration.collaborationMouse===true;input.classList.add('vmuMouseToggle');mouseLabel.classList.add('vmuMouseLabel');input.addEventListener('change',async e=>{e.stopPropagation();const desired=input.checked;input.disabled=true;try{const updated=await setMouseCapability(monitor,desired);monitor.configuration.collaborationMouse=updated.configuration.collaborationMouse;input.checked=updated.configuration.collaborationMouse===true;toast('Mouse portal '+(input.checked?'enabled.':'disabled.'));}catch(error){input.checked=!desired;toast(error?.message||'Mouse capability could not be changed.',true);}finally{input.disabled=false;}});}}if(!menu.querySelector('.vmuAudioDisabled')){const hr=menu.querySelector('hr');const audio=document.createElement('label');audio.className='vmuAudioDisabled';audio.title='Audio control is not implemented yet.';audio.innerHTML='<input type="checkbox" disabled> Audio';if(hr)menu.insertBefore(audio,hr);else menu.appendChild(audio);}});}
  async function monitorChoices(){const a=await fetch('/api/monitors',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();});return a.filter(m=>m.connected&&!m.health.isError);}
  async function openCamera(){try{const path=location.pathname;const direct=path.startsWith('/monitor/')?decodeURIComponent(path.substring('/monitor/'.length)):null;if(direct){await captureFromClick(direct);return;}const monitors=await monitorChoices();if(monitors.length===0){toast('No connected monitor is available for a screenshot.',true);return;}if(monitors.length===1){await captureFromClick(monitors[0].configuration.name);return;}cameraMenu.innerHTML='';for(const m of monitors){const b=document.createElement('button');b.type='button';b.textContent='📷 '+m.configuration.title;b.onclick=e=>{e.stopPropagation();cameraMenu.classList.add('hidden');captureFromClick(m.configuration.name);};cameraMenu.appendChild(b);}cameraMenu.classList.remove('hidden');}catch{toast('Monitor list is unavailable.',true);}}
  camera?.addEventListener('click',e=>{e.stopPropagation();openCamera();});document.addEventListener('click',()=>cameraMenu?.classList.add('hidden'));
  if(navHost)new MutationObserver(()=>{decorateMenus();renderBuiltInAvatars();}).observe(navHost,{childList:true,subtree:true});const grid=document.getElementById('grid');if(grid)new MutationObserver(()=>renderBuiltInAvatars()).observe(grid,{childList:true,subtree:true});decorateMenus();loadAvatarData();
})();
</script>
""";

    public const string Settings = """
<script>
(() => {
  const form=document.getElementById('form'),preview=document.getElementById('preview'),exit=document.getElementById('exit');if(!form||!preview||!exit)return;
  [...exit.options].filter(x=>x.value==='Uninstall'||x.text==='Uninstall').forEach(x=>x.remove());const previewRow=preview.closest('div.formgrid');if(previewRow&&!document.getElementById('snapTolerance')){const label=document.createElement('label');label.textContent='Arrangement Snap';const host=document.createElement('div');host.innerHTML='<input id="snapTolerance" class="smallNumber" type="number" min="5" max="50" step="1"> px';previewRow.append(label,host);}const snap=document.getElementById('snapTolerance');let settingsSnapshot=null;fetch('/api/settings',{cache:'no-store'}).then(r=>r.json()).then(s=>{settingsSnapshot=s;if(snap)snap.value=Math.min(50,Math.max(5,s.webUi?.arrangementSnapTolerancePx??15));if(exit.value==='Uninstall')exit.value='Disconnect';}).catch(()=>{});
  form.onsubmit=async e=>{e.preventDefault();dependency();const base=settingsSnapshot||original;const x={vmu:{interface:q('vmuInterface').value,port:+q('vmuPort').value},web:{interface:q('webInterface').value,port:+q('webPort').value},socket:{interface:q('socketInterface').value,port:+q('socketPort').value},logging:{retentionMinutes:+q('retention').value*1440},webUi:{monitorPreviewRefreshSeconds:+q('preview').value,arrangementSnapTolerancePx:Math.min(50,Math.max(5,+(snap?.value||15)))},exit:{monitorAction:q('exit').value==='Keep'?'Keep':'Disconnect',restoreServices:q('restore').checked},serviceState:base.serviceState};const r=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});if(!r.ok){q('error').textContent=(await r.json()).error;return;}const result=await r.json();if(result.restartRequired)location.href=result.targetUrl;else location.reload();};
})();
</script>
""";

    public const string Monitors = """
<style>
.monitorcard.dragging{opacity:1!important;border-color:#246bce;transition:none}.monitorcard.dragSource{opacity:1!important}.vmuDragGhost{position:fixed!important;z-index:5000!important;pointer-events:none!important;opacity:.92!important;box-shadow:0 10px 28px #0005!important;margin:0!important}.vmuDragGhost .cardtools{display:none!important}.monitorcard.dropBefore{box-shadow:-5px 0 0 #246bce}.monitorcard.dropAfter{box-shadow:5px 0 0 #246bce}.addmonitor,.addmonitor:visited{color:#202124!important;text-decoration:none!important}.addmonitor .plus{color:#202124!important;font-size:54px!important;line-height:1!important;margin:0!important}.addmonitor .plus::after{display:none!important}.addmonitor h3{color:#202124!important;text-decoration:none!important;margin:16px 0 0!important}.monitorpic{cursor:default}
</style>
<script>
(() => {
  const grid=document.getElementById('grid');if(!grid)return;
  async function persistOrder(){const response=await fetch('/api/monitors/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[...grid.querySelectorAll('.monitorcard[data-id]')].map(x=>x.dataset.id)})});if(!response.ok)throw new Error('Monitor order could not be saved.');await window.vmuRefreshMonitorNav?.();}
  function clearTargets(){grid.querySelectorAll('.dropBefore,.dropAfter').forEach(x=>x.classList.remove('dropBefore','dropAfter'));}
  function wireStableDrag(){grid.querySelectorAll('.move').forEach(old=>{if(old.dataset.vmuStableDrag==='1')return;const handle=old.cloneNode(true);handle.dataset.vmuStableDrag='1';old.replaceWith(handle);let card=null,pointer=null,ghost=null,offsetX=0,offsetY=0,dropTarget=null,dropBefore=false;handle.onpointerdown=e=>{if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();e.stopPropagation();card=handle.closest('.monitorcard[data-id]');if(!card)return;pointer=e.pointerId;dropTarget=null;dropBefore=false;handle.setPointerCapture(pointer);const r=card.getBoundingClientRect();offsetX=e.clientX-r.left;offsetY=e.clientY-r.top;ghost=card.cloneNode(true);ghost.classList.add('vmuDragGhost');ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';ghost.style.left=(e.clientX-offsetX)+'px';ghost.style.top=(e.clientY-offsetY)+'px';document.body.appendChild(ghost);card.classList.add('dragging');};handle.onpointermove=e=>{if(!card||e.pointerId!==pointer)return;e.preventDefault();if(ghost){ghost.style.left=(e.clientX-offsetX)+'px';ghost.style.top=(e.clientY-offsetY)+'px';}clearTargets();dropTarget=document.elementFromPoint(e.clientX,e.clientY)?.closest('.monitorcard[data-id]')||null;if(!dropTarget||dropTarget===card){dropTarget=null;return;}const r=dropTarget.getBoundingClientRect();const horizontal=Math.abs(e.clientX-(r.left+r.width/2))>=Math.abs(e.clientY-(r.top+r.height/2));dropBefore=horizontal?e.clientX<r.left+r.width/2:e.clientY<r.top+r.height/2;dropTarget.classList.add(dropBefore?'dropBefore':'dropAfter');};const finish=async e=>{if(!card||(e&&e.pointerId!==pointer))return;const moving=card,target=dropTarget,before=dropBefore;try{if(pointer!==null&&handle.hasPointerCapture(pointer))handle.releasePointerCapture(pointer);}catch{}clearTargets();moving.classList.remove('dragging','dragSource');ghost?.remove();card=null;ghost=null;pointer=null;dropTarget=null;if(target&&target!==moving)grid.insertBefore(moving,before?target:target.nextSibling);try{await persistOrder();}catch(error){console.error(error);}};handle.onpointerup=finish;handle.onpointercancel=finish;});}
  function wireTerminalDoubleClick(){grid.querySelectorAll('.monitorpic').forEach(pic=>{if(pic.dataset.vmuTerminal==='1')return;pic.dataset.vmuTerminal='1';let clickTimer=null;pic.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();clearTimeout(clickTimer);const href=pic.closest('a')?.href;clickTimer=setTimeout(()=>{if(href)location.href=href;},280);});pic.addEventListener('dblclick',e=>{e.preventDefault();e.stopPropagation();clearTimeout(clickTimer);const card=pic.closest('.monitorcard[data-id]'),preview=pic.querySelector('.preview:not(.hidden)'),href=pic.closest('a')?.getAttribute('href');if(!preview||!href){if(href)location.href=href;return;}const marker='/monitors/';const at=href.indexOf(marker);if(at>=0)location.href='/monitor/'+href.substring(at+marker.length);});});}
  const observer=new MutationObserver(()=>{wireStableDrag();wireTerminalDoubleClick();});observer.observe(grid,{childList:true,subtree:true});wireStableDrag();wireTerminalDoubleClick();
})();
</script>
""";

    public const string Terminal = """
<style>
#terminalFreeze{position:absolute;inset:0;margin:auto;max-width:100%;max-height:100%;width:auto;height:auto;z-index:2;pointer-events:none;opacity:0;visibility:hidden;filter:none;transition:opacity .18s ease,filter .18s ease}#terminalFreeze.reconnecting{visibility:visible;opacity:.52;filter:blur(6px)}#live{z-index:1;cursor:default}.terminalStarting{position:absolute;inset:0;z-index:4;display:flex;align-items:center;justify-content:center;background:#292b2f;color:#fff}.terminalStartingCard{width:min(380px,70vw);text-align:center}.terminalStartingCard h2{margin:0 0 16px}.terminalStartingProgress{height:6px;background:#4a4e54;border-radius:4px;overflow:hidden}.terminalStartingProgress>div{height:100%;width:32%;background:#5b9cff;border-radius:4px;animation:terminalThirst 1.05s ease-in-out infinite}@keyframes terminalThirst{0%{transform:translateX(-110%)}100%{transform:translateX(330%)}}
</style>
<script>
(() => {
  let previousReady=null;const live=document.getElementById('live');if(!live)return;live.alt='';const monitorName=decodeURIComponent(location.pathname.substring('/monitor/'.length));const mouseUrl='/api/monitors/'+encodeURIComponent(monitorName)+'/mouse',portalUrl=mouseUrl+'/portal';const terminalPage=live.closest('.terminalPage');const freeze=document.createElement('canvas');freeze.id='terminalFreeze';freeze.setAttribute('aria-hidden','true');terminalPage?.insertBefore(freeze,live.nextSibling);const starting=document.createElement('div');starting.className='terminalStarting';starting.innerHTML='<div class="terminalStartingCard"><h2>Terminal is starting…</h2><div class="terminalStartingProgress"><div></div></div></div>';terminalPage?.appendChild(starting);const freezeContext=freeze.getContext('2d',{alpha:false});let haveFreeze=false,reconnecting=false,frameTimer=null,mouseAllowed=null,mouseHandoff=false,firstFrame=false;
  function rememberFrame(){if(document.hidden||!live.naturalWidth||!live.naturalHeight||live.classList.contains('hidden'))return;try{if(freeze.width!==live.naturalWidth||freeze.height!==live.naturalHeight){freeze.width=live.naturalWidth;freeze.height=live.naturalHeight;}freezeContext?.drawImage(live,0,0,freeze.width,freeze.height);haveFreeze=true;}catch{}}
  function showReconnectFrame(){rememberFrame();reconnecting=true;if(firstFrame&&haveFreeze)freeze.classList.add('reconnecting');live.style.opacity='0';if(!firstFrame)starting.classList.remove('hidden');}
  function showLiveFrame(){if(!live.naturalWidth||!live.naturalHeight)return;firstFrame=true;reconnecting=false;live.style.opacity='1';freeze.classList.remove('reconnecting');starting.classList.add('hidden');rememberFrame();}
  live.addEventListener('error',showReconnectFrame);live.addEventListener('load',showLiveFrame);frameTimer=setInterval(()=>{if(!reconnecting)rememberFrame();if(reconnecting&&live.naturalWidth>0&&live.naturalHeight>0)showLiveFrame();},1000);window.addEventListener('beforeunload',()=>clearInterval(frameTimer),{once:true});
  async function reconnectTerminal(){try{const [s,m]=await Promise.all([fetch('/api/status',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();}),fetch(location.pathname.replace('/monitor/','/api/monitors/'),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();})]);const vmu=s.services.find(x=>x.key==='VMU_SERVER')?.running===true;const ready=vmu&&m.connected&&!m.health.isError;mouseAllowed=m.configuration?.collaborationMouse===true;if(ready&&previousReady===false){showReconnectFrame();stopStream();startStream();}else if(!ready){showReconnectFrame();stopStream();}previousReady=ready;}catch{mouseAllowed=null;previousReady=false;showReconnectFrame();stopStream();}}
  async function postMouse(payload){const response=await fetch(mouseUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok){let message='Terminal mouse input failed.';try{message=(await response.json()).error||message;}catch{}throw new Error(message);}}
  function renderedPoint(e){const rect=live.getBoundingClientRect();if(rect.width<=0||rect.height<=0)return null;const x=e.clientX-rect.left,y=e.clientY-rect.top;if(x<0||y<0||x>rect.width||y>rect.height)return null;return{x:Math.max(0,Math.min(1,x/rect.width)),y:Math.max(0,Math.min(1,y/rect.height)),rect};}
  async function refreshAfterPortal(){let seen=false;for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,50));try{const state=await fetch(portalUrl,{cache:'no-store'}).then(r=>r.json());if(state.active){seen=true;continue;}if(seen){rememberFrame();stopStream();startStream();return;}}catch{return;}}}
  live.addEventListener('click',async e=>{if(mouseHandoff||reconnecting||live.classList.contains('hidden'))return;if(mouseAllowed!==true)return;const point=renderedPoint(e);if(!point)return;mouseHandoff=true;try{const ox=e.screenX-e.clientX,oy=e.screenY-e.clientY;const left=Math.round(ox+point.rect.left),top=Math.round(oy+point.rect.top),right=Math.round(ox+point.rect.right),bottom=Math.round(oy+point.rect.bottom);await postMouse({type:'portalbounds',x:null,y:null,button:left,delta:top});await postMouse({type:'portal',x:point.x,y:point.y,button:right,delta:bottom});refreshAfterPortal();}catch{}finally{mouseHandoff=false;}});
  reconnectTerminal();setInterval(reconnectTerminal,750);window.addEventListener('online',reconnectTerminal);window.addEventListener('pageshow',reconnectTerminal);
})();
</script>
""";

    public const string Log = """
<script>
(() => {const actions=document.querySelector('.logActions');if(!actions||document.getElementById('logCancel'))return;const cancel=document.createElement('button');cancel.id='logCancel';cancel.type='button';cancel.textContent='Cancel';cancel.onclick=()=>location.href='/';actions.appendChild(cancel);})();
</script>
""";
}
