<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>vmu</AssemblyName>
    <RootNamespace>VirtualMonitorsUniverse.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.0" />
  </ItemGroup>
</Project>
