[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo_root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$log_path = Join-Path $repo_root 'multivddtest.log'
$runtime_root = Join-Path $repo_root '.runtime\alpha'
$inf_path = Join-Path $runtime_root 'vdd-source\MttVDD.inf'
$cat_path = Join-Path $runtime_root 'vdd-source\mttvdd.cat'
$nefcon_exe = Join-Path $runtime_root 'work\nefcon\x64\nefconw.exe'
$topology_helper = Join-Path $PSScriptRoot 'displayconfig-topology.ps1'
$minimum_adjacency = 64

function Write-Log {
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Message,[ConsoleColor]$Color = [ConsoleColor]::Gray)
    $line = '[{0}] {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'), $Message
    Add-Content -LiteralPath $log_path -Value $line -Encoding UTF8
    Write-Host $Message -ForegroundColor $Color
}
function Invoke-Native { param([string]$FilePath,[string[]]$Arguments,[switch]$AllowFailure); Write-Log ("RUN: {0} {1}" -f $FilePath,($Arguments -join ' ')) DarkGray; $p=Start-Process -FilePath $FilePath -ArgumentList $Arguments -Wait -PassThru -NoNewWindow; Write-Log "EXIT CODE: $($p.ExitCode)" DarkGray; if(-not $AllowFailure -and $p.ExitCode-ne0){throw "$FilePath failed with exit code $($p.ExitCode)."}; return $p.ExitCode }
function Wait-Until { param([scriptblock]$Condition,[string]$Description,[int]$TimeoutMs=10000); $sw=[Diagnostics.Stopwatch]::StartNew(); do{if(& $Condition){Write-Log ("READY after {0} ms: {1}"-f$sw.ElapsedMilliseconds,$Description) DarkGray;return $true};Start-Sleep -Milliseconds 100}while($sw.ElapsedMilliseconds-lt$TimeoutMs);Write-Log ("TIMEOUT after {0} ms: {1}"-f$sw.ElapsedMilliseconds,$Description) Yellow;return $false }
function Ask-User { param([string]$Prompt); while($true){$a=(Read-Host "$Prompt [Y/N]").Trim().ToUpperInvariant();if($a-eq'Y'){Write-Log "USER CONFIRMATION: YES - $Prompt" Green;return $true};if($a-eq'N'){Write-Log "USER CONFIRMATION: NO - $Prompt" Red;return $false}} }
function Get-Vdds { return @(Get-PnpDevice -Class Display -ErrorAction SilentlyContinue|Where-Object FriendlyName -eq 'Virtual Display Driver') }

function Ensure-VmuReflowApi {
 if('Vmu.ReflowV10Api' -as [type]){return}
 Add-Type -AssemblyName System.Windows.Forms
 Add-Type -AssemblyName System.Drawing
 Add-Type -ReferencedAssemblies @('System.Windows.Forms.dll','System.Drawing.dll') -TypeDefinition @'
using System;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Text;
namespace Vmu{public static class ReflowV10Api{
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] public struct DEVMODE{[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string dmDeviceName;public ushort dmSpecVersion,dmDriverVersion,dmSize,dmDriverExtra;public uint dmFields;public int dmPositionX,dmPositionY;public uint dmDisplayOrientation,dmDisplayFixedOutput;public short dmColor,dmDuplex,dmYResolution,dmTTOption,dmCollate;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string dmFormName;public ushort dmLogPixels;public uint dmBitsPerPel,dmPelsWidth,dmPelsHeight,dmDisplayFlags,dmDisplayFrequency,dmICMMethod,dmICMIntent,dmMediaType,dmDitherType,dmReserved1,dmReserved2,dmPanningWidth,dmPanningHeight;}
 [StructLayout(LayoutKind.Sequential)]public struct RECT{public int Left,Top,Right,Bottom;}[StructLayout(LayoutKind.Sequential)]public struct LUID{public uint LowPart;public int HighPart;}[StructLayout(LayoutKind.Sequential)]public struct RATIONAL{public uint Numerator,Denominator;}[StructLayout(LayoutKind.Sequential)]public struct POINTL{public int x,y;}[StructLayout(LayoutKind.Sequential)]public struct SOURCE_MODE{public uint width,height,pixelFormat;public POINTL position;}[StructLayout(LayoutKind.Explicit,Size=48)]public struct MODE_UNION{[FieldOffset(0)]public SOURCE_MODE sourceMode;}[StructLayout(LayoutKind.Sequential)]public struct MODE{public uint infoType,id;public LUID adapterId;public MODE_UNION modeInfo;}[StructLayout(LayoutKind.Sequential)]public struct PATH_SOURCE{public LUID adapterId;public uint id,modeInfoIdx,statusFlags;}[StructLayout(LayoutKind.Sequential)]public struct PATH_TARGET{public LUID adapterId;public uint id,modeInfoIdx,outputTechnology,rotation,scaling;public RATIONAL refreshRate;public uint scanLineOrdering;[MarshalAs(UnmanagedType.Bool)]public bool targetAvailable;public uint statusFlags;}[StructLayout(LayoutKind.Sequential)]public struct PATH{public PATH_SOURCE sourceInfo;public PATH_TARGET targetInfo;public uint flags;}[StructLayout(LayoutKind.Sequential)]public struct HEADER{public uint type,size;public LUID adapterId;public uint id;}[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public struct SOURCE_NAME{public HEADER header;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string viewGdiDeviceName;}
 public class WindowState{public IntPtr Hwnd;public string Title,Screen;public int RelativeX,RelativeY,Width,Height;}public class SourceState{public string GdiName,SourceKey;public int X,Y;public uint Width,Height;}
 const uint QDC=2,USE=0x20,VALIDATE=0x40,APPLY=0x80,SAVE=0x200,SOURCE=1,GET_SOURCE=1;const int CURRENT=-1;delegate bool EnumWindowsProc(IntPtr h,IntPtr l);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool EnumDisplaySettings(string n,int i,ref DEVMODE m);[DllImport("user32.dll")]static extern int GetDisplayConfigBufferSizes(uint f,out uint pc,out uint mc);[DllImport("user32.dll")]static extern int QueryDisplayConfig(uint f,ref uint pc,[Out]PATH[]p,ref uint mc,[Out]MODE[]m,IntPtr t);[DllImport("user32.dll")]static extern int SetDisplayConfig(uint pc,PATH[]p,uint mc,MODE[]m,uint f);[DllImport("user32.dll")]static extern int DisplayConfigGetDeviceInfo(ref SOURCE_NAME p);[DllImport("user32.dll")]static extern bool EnumWindows(EnumWindowsProc p,IntPtr l);[DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr h);[DllImport("user32.dll")]static extern bool IsIconic(IntPtr h);[DllImport("user32.dll")]static extern bool GetWindowRect(IntPtr h,out RECT r);[DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetWindowText(IntPtr h,StringBuilder s,int n);
 static string Luid(LUID v){return v.HighPart.ToString("X8")+":"+v.LowPart.ToString("X8");}
 public static WindowState[] Windows(){var list=new List<WindowState>();EnumWindows(delegate(IntPtr h,IntPtr l){if(!IsWindowVisible(h)||IsIconic(h))return true;RECT r;if(!GetWindowRect(h,out r)||r.Right<=r.Left||r.Bottom<=r.Top)return true;var sc=System.Windows.Forms.Screen.FromHandle(h);var sb=new StringBuilder(256);GetWindowText(h,sb,sb.Capacity);list.Add(new WindowState{Hwnd=h,Title=sb.ToString(),Screen=sc.DeviceName,RelativeX=r.Left-sc.Bounds.Left,RelativeY=r.Top-sc.Bounds.Top,Width=r.Right-r.Left,Height=r.Bottom-r.Top});return true;},IntPtr.Zero);return list.ToArray();}
 public static SourceState[] ActiveSources(){uint pc,mc;int r=GetDisplayConfigBufferSizes(QDC,out pc,out mc);if(r!=0)throw new InvalidOperationException("GetDisplayConfigBufferSizes failed: "+r);var paths=new PATH[pc];var modes=new MODE[mc];r=QueryDisplayConfig(QDC,ref pc,paths,ref mc,modes,IntPtr.Zero);if(r!=0)throw new InvalidOperationException("QueryDisplayConfig failed: "+r);var list=new List<SourceState>();for(int i=0;i<pc;i++){uint mi=paths[i].sourceInfo.modeInfoIdx;if(mi>=mc||modes[mi].infoType!=SOURCE)continue;var sn=new SOURCE_NAME();sn.header.type=GET_SOURCE;sn.header.size=(uint)Marshal.SizeOf(typeof(SOURCE_NAME));sn.header.adapterId=paths[i].sourceInfo.adapterId;sn.header.id=paths[i].sourceInfo.id;if(DisplayConfigGetDeviceInfo(ref sn)!=0)continue;var sm=modes[mi].modeInfo.sourceMode;list.Add(new SourceState{GdiName=sn.viewGdiDeviceName,SourceKey=Luid(paths[i].sourceInfo.adapterId)+"/"+paths[i].sourceInfo.id,X=sm.position.x,Y=sm.position.y,Width=sm.width,Height=sm.height});}return list.ToArray();}
 public static int ApplyPlan(string[]keys,int[]xs,int[]ys,uint[]ws,uint[]hs){uint pc,mc;int r=GetDisplayConfigBufferSizes(QDC,out pc,out mc);if(r!=0)return r;var paths=new PATH[pc];var modes=new MODE[mc];r=QueryDisplayConfig(QDC,ref pc,paths,ref mc,modes,IntPtr.Zero);if(r!=0)return r;var map=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);for(int i=0;i<keys.Length;i++)map[keys[i]]=i;for(int i=0;i<pc;i++){uint mi=paths[i].sourceInfo.modeInfoIdx;if(mi>=mc||modes[mi].infoType!=SOURCE)continue;int k;if(!map.TryGetValue(Luid(paths[i].sourceInfo.adapterId)+"/"+paths[i].sourceInfo.id,out k))continue;var s=modes[mi].modeInfo.sourceMode;s.position.x=xs[k];s.position.y=ys[k];s.width=ws[k];s.height=hs[k];var u=modes[mi].modeInfo;u.sourceMode=s;modes[mi].modeInfo=u;}r=SetDisplayConfig(pc,paths,mc,modes,USE|VALIDATE);if(r!=0)return r;return SetDisplayConfig(pc,paths,mc,modes,USE|APPLY|SAVE);}
}}
'@
}

function Get-DisplaySnapshot { Ensure-VmuReflowApi; $r=@(); foreach($s in @([Vmu.ReflowV10Api]::ActiveSources())){$r+=[pscustomobject]@{DeviceName=[string]$s.GdiName;SourceKey=[string]$s.SourceKey;X=[int]$s.X;Y=[int]$s.Y;Width=[int]$s.Width;Height=[int]$s.Height}};return @($r) }
function Get-Overlap([int]$A1,[int]$A2,[int]$B1,[int]$B2){return [Math]::Max(0,[Math]::Min($A2,$B2)-[Math]::Max($A1,$B1))}
function Test-RectsOverlap {param($RectA,$RectB);return ((Get-Overlap $RectA.X ($RectA.X+$RectA.Width) $RectB.X ($RectB.X+$RectB.Width))-gt0 -and (Get-Overlap $RectA.Y ($RectA.Y+$RectA.Height) $RectB.Y ($RectB.Y+$RectB.Height))-gt0)}
function Get-BestAdjacencyAnchor {param([object[]]$Snapshot,[string]$TargetDeviceName);$t=$Snapshot|Where-Object DeviceName -eq $TargetDeviceName|Select-Object -First 1;if($null-eq$t){throw "Target $TargetDeviceName missing."};$c=@();$tr=$t.X+$t.Width;$tb=$t.Y+$t.Height;foreach($o in @($Snapshot|Where-Object DeviceName -ne $TargetDeviceName)){$or=$o.X+$o.Width;$ob=$o.Y+$o.Height;$v=Get-Overlap $t.Y $tb $o.Y $ob;$h=Get-Overlap $t.X $tr $o.X $or;if($t.X-eq$or-and$v-ge$minimum_adjacency){$c+=[pscustomobject]@{Side='Left';Neighbor=$o;Overlap=$v}};if($tr-eq$o.X-and$v-ge$minimum_adjacency){$c+=[pscustomobject]@{Side='Right';Neighbor=$o;Overlap=$v}};if($t.Y-eq$ob-and$h-ge$minimum_adjacency){$c+=[pscustomobject]@{Side='Above';Neighbor=$o;Overlap=$h}};if($tb-eq$o.Y-and$h-ge$minimum_adjacency){$c+=[pscustomobject]@{Side='Below';Neighbor=$o;Overlap=$h}}};$best=$c|Sort-Object Overlap -Descending|Select-Object -First 1;if($null-eq$best){throw "Target $TargetDeviceName has no usable edge anchor."};return $best}

function New-ReflowPlan {
 param([object[]]$Snapshot,[string]$TargetDeviceName,[int]$NewWidth,[int]$NewHeight,$Anchor)
 $plan=@();foreach($d in $Snapshot){$plan+=[pscustomobject]@{DeviceName=$d.DeviceName;SourceKey=$d.SourceKey;X=[int]$d.X;Y=[int]$d.Y;Width=[int]$d.Width;Height=[int]$d.Height;OriginalX=[int]$d.X;OriginalY=[int]$d.Y;OriginalWidth=[int]$d.Width;OriginalHeight=[int]$d.Height;DeltaX=0;DeltaY=0}}
 $target_rect=$plan|Where-Object DeviceName -eq $TargetDeviceName|Select-Object -First 1;if($null-eq$target_rect){throw "Target $TargetDeviceName missing from plan."}
 $dw=$NewWidth-$target_rect.Width;$dh=$NewHeight-$target_rect.Height
 switch($Anchor.Side){'Left'{$target_rect.X=$Anchor.Neighbor.X+$Anchor.Neighbor.Width};'Right'{$target_rect.X=$Anchor.Neighbor.X-$NewWidth};'Above'{$target_rect.Y=$Anchor.Neighbor.Y+$Anchor.Neighbor.Height};'Below'{$target_rect.Y=$Anchor.Neighbor.Y-$NewHeight};default{throw "Unsupported anchor $($Anchor.Side)"}}
 $target_rect.Width=$NewWidth;$target_rect.Height=$NewHeight;$target_rect.DeltaX=$target_rect.X-$target_rect.OriginalX;$target_rect.DeltaY=$target_rect.Y-$target_rect.OriginalY
 $queue=New-Object System.Collections.Queue;$queued=New-Object 'System.Collections.Generic.HashSet[string]' ([StringComparer]::OrdinalIgnoreCase)
 foreach($d in @($plan|Where-Object DeviceName -ne $TargetDeviceName)){if(Test-RectsOverlap $target_rect $d){[void]$queued.Add($d.DeviceName);$queue.Enqueue($d)}}
 while($queue.Count-gt0){$d=$queue.Dequeue();if(Test-RectsOverlap $target_rect $d){$mr=($target_rect.X+$target_rect.Width)-$d.X;$ml=($d.X+$d.Width)-$target_rect.X;$md=($target_rect.Y+$target_rect.Height)-$d.Y;$mu=($d.Y+$d.Height)-$target_rect.Y;if($dw-ne0-and$dh-eq0){if($d.OriginalX-ge$target_rect.OriginalX){$d.X+=$mr}else{$d.X-=$ml}}elseif($dh-ne0-and$dw-eq0){if($d.OriginalY-ge$target_rect.OriginalY){$d.Y+=$md}else{$d.Y-=$mu}}elseif([Math]::Min($md,$mu)-le[Math]::Min($mr,$ml)){if($d.OriginalY-ge$target_rect.OriginalY){$d.Y+=$md}else{$d.Y-=$mu}}else{if($d.OriginalX-ge$target_rect.OriginalX){$d.X+=$mr}else{$d.X-=$ml}}};$d.DeltaX=$d.X-$d.OriginalX;$d.DeltaY=$d.Y-$d.OriginalY;foreach($o in @($plan|Where-Object {$_.DeviceName-ne$TargetDeviceName-and$_.DeviceName-ne$d.DeviceName})){if($queued.Contains($o.DeviceName)){continue};if(Test-RectsOverlap $d $o){$o.X+=$d.DeltaX;$o.Y+=$d.DeltaY;$o.DeltaX=$o.X-$o.OriginalX;$o.DeltaY=$o.Y-$o.OriginalY;[void]$queued.Add($o.DeviceName);$queue.Enqueue($o)}}}
 return @($plan)
}
function Assert-PlanNoOverlap {param([object[]]$Plan);for($i=0;$i-lt$Plan.Count;$i++){for($j=$i+1;$j-lt$Plan.Count;$j++){if(Test-RectsOverlap $Plan[$i] $Plan[$j]){throw "Reflow plan overlaps $($Plan[$i].DeviceName) and $($Plan[$j].DeviceName)."}}}}
function Apply-ReflowPlan {param([object[]]$Plan);$k=@();$x=@();$y=@();$w=@();$h=@();foreach($d in $Plan){$k+=[string]$d.SourceKey;$x+=[int]$d.X;$y+=[int]$d.Y;$w+=[uint32]$d.Width;$h+=[uint32]$d.Height};$r=[Vmu.ReflowV10Api]::ApplyPlan($k,$x,$y,$w,$h);if($r-ne0){throw "SetDisplayConfig reflow failed: $r"}}
function Test-ReflowWindows {param([object[]]$BeforeWindows,[object[]]$Plan,[string]$TargetDeviceName);Start-Sleep -Milliseconds 500;$after=@([Vmu.ReflowV10Api]::Windows());foreach($d in @($Plan|Where-Object {($_.DeltaX-ne0-or$_.DeltaY-ne0)-and$_.DeviceName-ne$TargetDeviceName})){foreach($b in @($BeforeWindows|Where-Object Screen -eq $d.DeviceName)){$a=$after|Where-Object Hwnd -eq $b.Hwnd|Select-Object -First 1;if($null-eq$a){continue};if($a.Screen-ne$d.DeviceName){throw "Window '$($b.Title)' moved to another monitor."};if($a.RelativeX-ne$b.RelativeX-or$a.RelativeY-ne$b.RelativeY-or$a.Width-ne$b.Width-or$a.Height-ne$b.Height){throw "Window '$($b.Title)' changed monitor-relative geometry on $($d.DeviceName)."}}};Write-Log 'PASS: windows on shifted monitors retained monitor-relative position and size.' Green}
function Resolve-LiveIdentity([string]$InstanceId,[string]$Label){$dev=Get-Vdds|Where-Object InstanceId -eq $InstanceId|Select-Object -First 1;if($null-eq$dev){throw "$Label missing."};$id=Resolve-VmuVddIdentity -Device $dev;if($null-eq$id){throw "$Label identity unavailable."};Write-Log ("LIVE IDENTITY {0}: instance={1}; gdi={2}; source={3}/{4}; target={5}/{6}"-f$Label,$id.InstanceId,$id.GdiName,$id.SourceLuid,$id.SourceId,$id.TargetLuid,$id.TargetId) DarkGray;return $id}
function Remove-OneVdd([string]$InstanceId){Invoke-Native "$env:SystemRoot\System32\pnputil.exe" @('/remove-device',('"{0}"'-f$InstanceId))|Out-Null;return Wait-Until {@(Get-Vdds|Where-Object InstanceId -eq $InstanceId).Count-eq0} "VDD $InstanceId removed" 5000}

Remove-Item -LiteralPath $log_path -Force -ErrorAction SilentlyContinue
. $topology_helper
Ensure-VmuReflowApi
Write-Log 'Virtual Monitors Universe - MULTI-VDD topology reflow acceptance test'
Write-Log 'Runner: multivdd-isolation-v10-anchor-aware-reflow' Cyan
Write-Log 'Rule: preserve the strongest existing edge anchor, then minimally reflow only displays that actually collide.' Cyan
Write-Log 'Physical and virtual displays are mapped deterministically through CCD source names; no Windows display number is required.' Cyan

try{
 if(@(Get-Vdds).Count-ne0){throw 'Multi-VDD test requires a clean baseline.'};foreach($f in @($inf_path,$cat_path,$nefcon_exe)){if(-not(Test-Path -LiteralPath $f)){throw "Missing ALPHA payload: $f"}}
 Write-Log 'Installing VDD A and VDD B...' Cyan;Invoke-Native $nefcon_exe @('install',('"{0}"'-f$inf_path),'Root\MttVDD')|Out-Null;if(-not(Wait-Until {@(Get-Vdds).Count-eq1} 'VDD A available')){throw 'VDD A did not appear.'};$a_device=@(Get-Vdds)[0];Invoke-Native $nefcon_exe @('install',('"{0}"'-f$inf_path),'Root\MttVDD')|Out-Null;if(-not(Wait-Until {@(Get-Vdds).Count-eq2} 'VDD B available')){throw 'VDD B did not appear.'}
 $devices=@(Get-Vdds|Sort-Object InstanceId);$a=$devices|Where-Object InstanceId -eq $a_device.InstanceId|Select-Object -First 1;$b=$devices|Where-Object InstanceId -ne $a_device.InstanceId|Select-Object -First 1;$a_id=$a.InstanceId;$b_id=$b.InstanceId;$ia=Resolve-LiveIdentity $a_id 'VDD-A';$ib=Resolve-LiveIdentity $b_id 'VDD-B';Write-Log "VDD-A = $($ia.GdiName); VDD-B = $($ib.GdiName)" Green
 $before=@(Get-DisplaySnapshot);foreach($d in $before){Write-Log ("BEFORE: {0}: ({1},{2}) {3}x{4}; source={5}"-f$d.DeviceName,$d.X,$d.Y,$d.Width,$d.Height,$d.SourceKey) DarkGray};$anchor=Get-BestAdjacencyAnchor $before $ia.GdiName;Write-Log ("ANCHOR: VDD-A side={0}; neighbor={1}; shared-edge={2}px"-f$anchor.Side,$anchor.Neighbor.DeviceName,$anchor.Overlap) Cyan
 $wb=@([Vmu.ReflowV10Api]::Windows());$grow=@(New-ReflowPlan $before $ia.GdiName 3840 2160 $anchor);foreach($d in $grow){Write-Log ("REFLOW-GROW: {0}: ({1},{2}) {3}x{4}; delta=({5},{6})"-f$d.DeviceName,$d.X,$d.Y,$d.Width,$d.Height,$d.DeltaX,$d.DeltaY) DarkGray};Assert-PlanNoOverlap $grow;Apply-ReflowPlan $grow;Test-ReflowWindows $wb $grow $ia.GdiName;if(-not(Ask-User 'Verify VDD-A is UHD, the layout remains connected, and windows on shifted monitors stayed in the same relative places')){throw 'User rejected grow reflow.'}
 $grown=@(Get-DisplaySnapshot);foreach($d in $grown){Write-Log ("GROWN: {0}: ({1},{2}) {3}x{4}"-f$d.DeviceName,$d.X,$d.Y,$d.Width,$d.Height) DarkGray};$orig=$before|Where-Object DeviceName -eq $ia.GdiName|Select-Object -First 1;$anchor2=Get-BestAdjacencyAnchor $grown $ia.GdiName;Write-Log ("SHRINK ANCHOR: side={0}; neighbor={1}; shared-edge={2}px"-f$anchor2.Side,$anchor2.Neighbor.DeviceName,$anchor2.Overlap) Cyan;$wb2=@([Vmu.ReflowV10Api]::Windows());$shrink=@(New-ReflowPlan $grown $ia.GdiName $orig.Width $orig.Height $anchor2);foreach($d in $shrink){Write-Log ("REFLOW-SHRINK: {0}: ({1},{2}) {3}x{4}; delta=({5},{6})"-f$d.DeviceName,$d.X,$d.Y,$d.Width,$d.Height,$d.DeltaX,$d.DeltaY) DarkGray};Assert-PlanNoOverlap $shrink;Apply-ReflowPlan $shrink;Test-ReflowWindows $wb2 $shrink $ia.GdiName;Write-Log 'PASS: grow and shrink completed with anchor-aware topology reflow.' Green
 $ia=Resolve-LiveIdentity $a_id 'VDD-A before disconnect';Invoke-VmuDisconnectExact -Identity $ia;if(-not(Wait-Until {(Test-VmuVddActive $a_id $false)-and(Test-VmuVddActive $b_id $true)} 'A disconnected while B remains active' 5000)){throw 'Disconnect isolation failed.'};Invoke-VmuReconnectSaved;if(-not(Wait-Until {(Test-VmuVddActive $a_id $true)-and(Test-VmuVddActive $b_id $true)} 'A reconnected while B remains active' 5000)){throw 'Reconnect isolation failed.'};if(-not(Remove-OneVdd $a_id)){throw 'Could not uninstall A.'};if(-not(Test-VmuVddActive $b_id $true)){throw 'Uninstalling A affected B.'};if(-not(Remove-OneVdd $b_id)){throw 'Could not uninstall B.'};Write-Log 'MULTI-VDD REFLOW ISOLATION: PASS' Green;exit 0
}catch{Write-Log "MULTI-VDD TEST ERROR: $($_.Exception.Message)" Red;foreach($d in @(Get-Vdds)){Invoke-Native "$env:SystemRoot\System32\pnputil.exe" @('/remove-device',('"{0}"'-f$d.InstanceId)) -AllowFailure|Out-Null};exit 1}
